steps:
#  # Retrieve the cached .m2 directory from GCS
#  - name: 'gcr.io/cloud-builders/gsutil'
#    args:
#      - '-m'
#      - 'rsync'
#      - '-r'
#      - 'gs://bucket-ci-cache/cache/.m2'
#      - '/cache/.m2'
#    volumes:
#      - path: '/cache/.m2'
#        name: 'm2_cache'

  # Build Maven
  - name: 'gcr.io/cloud-builders/mvn'
    args:
      - 'clean'
      - 'package'
      - '--batch-mode'
      - '-Dmaven.test.skip=true'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
    env:
      - MAVEN_OPTS=-Dmaven.repo.local=/cache/.m2

#  # Update cached .m2 directory on GCS with any additional dependencies downloaded during the build.
#  - name: 'gcr.io/cloud-builders/gsutil'
#    args:
#      - '-m'
#      - 'rsync'
#      - '-r'
#      - '/cache/.m2'
#      - 'gs://bucket-ci-cache/cache/.m2/'
#    volumes:
#      - path: '/cache/.m2'
#        name: 'm2_cache'

  # Build docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '$_IMAGE_NAME:$COMMIT_SHA'
      - .
      - '-f'
      - $_DOCKERFILE_NAME
    dir: $_DOCKERFILE_DIR
    id: Build

  # Push docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_IMAGE_NAME:$COMMIT_SHA'
    id: Push

  # GKE deploy
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - prepare
      - '--filename=$_K8S_YAML_PATH'
      - '--image=$_IMAGE_NAME:$COMMIT_SHA'
      - '--app=$_K8S_APP_NAME'
      - '--version=$COMMIT_SHA'
      - '--namespace=$_K8S_NAMESPACE'
      - '--label=$_K8S_LABELS'
      - '--annotation=$_K8S_ANNOTATIONS,gcb-build-id=$BUILD_ID'
      - '--create-application-cr'
      - >-
        --links="Build
        details=https://console.cloud.google.com/cloud-build/builds/$BUILD_ID?project=$PROJECT_ID"
      - '--output=output'
    id: Prepare deploy
  - name: gcr.io/cloud-builders/gsutil
    args:
      - '-c'
      - |-
        if [ "$_OUTPUT_BUCKET_PATH" != "" ]
        then
          gsutil cp -r output/suggested gs://$_OUTPUT_BUCKET_PATH/config/$_K8S_APP_NAME/$BUILD_ID/suggested
          gsutil cp -r output/expanded gs://$_OUTPUT_BUCKET_PATH/config/$_K8S_APP_NAME/$BUILD_ID/expanded
        fi
    id: Save configs
    entrypoint: sh
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - apply
      - '--filename=output/expanded'
      - '--cluster=$_GKE_CLUSTER'
      - '--location=$_GKE_LOCATION'
      - '--namespace=$_K8S_NAMESPACE'
    id: Apply deploy
images:
  - '$_IMAGE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _K8S_NAMESPACE: default
  _OUTPUT_BUCKET_PATH: flnk-370323_cloudbuild/deploy
  _DOCKERFILE_NAME: Dockerfile
  _K8S_LABELS: ''
  _K8S_YAML_PATH: kubernetes/
  _GKE_CLUSTER: quickstart-cluster-qsdev
  _GKE_LOCATION: europe-west4
  _DOCKERFILE_DIR: ''
  _K8S_ANNOTATIONS: gcb-trigger-id=dad9533a-9f68-4b71-a922-ede117a0f2dd
  _IMAGE_NAME: gcr.io/flnk-370323/github.com/masoud91/flk
  _K8S_APP_NAME: flnk
tags:
  - gcp-cloud-build-deploy
  - $_K8S_APP_NAME
